# Generated by Django 5.2 on 2025-04-19 06:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('premio_primero', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('premio_segundo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('premio_tercero', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('premio_cuarto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_inscripcion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('pago_completo', models.BooleanField(default=False)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_equipos/')),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B')], max_length=1, null=True)),
                ('nivel', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Muy bajo'), (2, '2 - Bajo'), (3, '3 - Medio'), (4, '4 - Alto'), (5, '5 - Muy alto')], null=True, verbose_name='Nivel')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='api.categoria')),
            ],
            options={
                'unique_together': {('nombre', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula', models.CharField(max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Muy bajo'), (2, '2 - Bajo'), (3, '3 - Medio'), (4, '4 - Alto'), (5, '5 - Muy alto')], null=True, verbose_name='Nivel')),
                ('cedula_imagen', models.ImageField(blank=True, null=True, upload_to='cedulas_jugadores/', verbose_name='Imagen de la cédula')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='api.equipo')),
            ],
            options={
                'unique_together': {('cedula', 'equipo')},
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('goles_equipo_1', models.PositiveSmallIntegerField(default=0)),
                ('goles_equipo_2', models.PositiveSmallIntegerField(default=0)),
                ('jugado', models.BooleanField(default=False)),
                ('fecha_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('equipo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo_1', to='api.equipo')),
                ('equipo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo_2', to='api.equipo')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='api.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minuto (opcional)')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='api.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='api.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AMARILLA', 'Amarilla'), ('ROJA', 'Roja')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('multa_pagada', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='api.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='api.partido')),
            ],
        ),
    ]
