# Generated by Django 5.2 on 2025-05-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionpago',
            name='es_ingreso',
            field=models.BooleanField(default=False, help_text='True si es un ingreso para el torneo, False si es un gasto'),
        ),
    ]
