# Generated by Django 5.2 on 2025-05-13 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaccionpago_es_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionpago',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='api.equipo'),
        ),
        migrations.AlterField(
            model_name='transaccionpago',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jugador'),
        ),
        migrations.AlterField(
            model_name='transaccionpago',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_pago', to='api.partido'),
        ),
    ]
