# Generated by Django 5.2 on 2025-05-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transaccionpago_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='numero_dorsal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
