# Generated by Django 5.2 on 2025-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_jugador_numero_dorsal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(condition=models.Q(('cedula__isnull', False)), fields=('cedula', 'equipo'), name='unique_cedula_equipo'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_dorsal__isnull', False)), fields=('equipo', 'numero_dorsal'), name='unique_equipo_dorsal'),
        ),
    ]
