# Generated by Django 5.2 on 2025-05-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_jugador_cedula_jugador_unique_cedula_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Muy bajo'), (2, '2 - Bajo'), (3, '3 - Medio'), (4, '4 - Alto'), (5, '5 - Muy alto')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
