# Generated by Django 5.2 on 2025-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_jugador_nivel_alter_jugador_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('suspendido', 'Suspendido')], default='activo', max_length=15),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
