# Generated by Django 5.2 on 2025-05-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_jugador_nivel_alter_jugador_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('suspendido', 'Suspendido')], default='activo', max_length=15),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='fecha_real_transaccion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de la transacción'),
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('deposito', 'Depósito Bancario'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='referencia_pago',
            field=models.CharField(blank=True, help_text='Número de referencia de transferencia, recibo, etc.', max_length=100),
        ),
    ]
