# Generated by Django 5.2 on 2025-05-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_equipo_estado_equipo_fecha_retiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='equipo_ganador_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victorias_por_default', to='api.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='victoria_por_default',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('retiro', 'Retiro de equipo'), ('inasistencia', 'Inasistencia'), ('sancion', 'Sanción administrativa')], max_length=20),
        ),
    ]
