# Generated by Django 5.2 on 2025-05-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_equipo_estado_equipo_fecha_retiro_and_more'),
    ]

    operations = [
        # Añadimos solo los campos de TransaccionPago que necesitamos
        migrations.AddField(
            model_name='transaccionpago',
            name='fecha_real_transaccion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de la transacción'),
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='metodo_pago',
            field=models.CharField(blank=True, default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='referencia_pago',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]