# Generated by Django 5.2 on 2025-06-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_partido_equipo_ganador_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='activo_segunda_fase',
            field=models.BooleanField(default=True),
        ),
    ]
