# Generated by Django 5.2.3 on 2025-06-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_jugador_activo_segunda_fase'),
    ]

    operations = [
        # Índices para mejorar rendimiento de búsquedas y filtros
        
        # Índice en jugador.cedula para búsquedas rápidas por cédula
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_jugador_cedula ON api_jugador (cedula) WHERE cedula IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS idx_jugador_cedula;"
        ),
        
        # Índice en jugador.equipo_id para filtros por equipo (ya existe FK pero mejoramos)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_jugador_equipo_id ON api_jugador (equipo_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_jugador_equipo_id;"
        ),
        
        # Índice en partido.fecha para búsquedas y ordenamiento por fecha
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_partido_fecha ON api_partido (fecha);",
            reverse_sql="DROP INDEX IF EXISTS idx_partido_fecha;"
        ),
        
        # Índice en partido.torneo_id para filtros por torneo (ya existe FK pero mejoramos)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_partido_torneo_id ON api_partido (torneo_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_partido_torneo_id;"
        ),
        
        # Índice compuesto en partido para consultas comunes (torneo + fecha)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_partido_torneo_fecha ON api_partido (torneo_id, fecha);",
            reverse_sql="DROP INDEX IF EXISTS idx_partido_torneo_fecha;"
        ),
        
        # Índice en tarjeta.jugador_id para búsquedas de tarjetas por jugador
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_tarjeta_jugador_id ON api_tarjeta (jugador_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_tarjeta_jugador_id;"
        ),
        
        # Índice compuesto en tarjeta para consultas de multas pendientes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_tarjeta_jugador_pagada ON api_tarjeta (jugador_id, pagada);",
            reverse_sql="DROP INDEX IF EXISTS idx_tarjeta_jugador_pagada;"
        ),
        
        # Índice en gol.partido_id para consultas de goles por partido
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_gol_partido_id ON api_gol (partido_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_gol_partido_id;"
        ),
        
        # Índice en gol.jugador_id para estadísticas de goleadores
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_gol_jugador_id ON api_gol (jugador_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_gol_jugador_id;"
        ),
    ]
