# Generated by Django 5.2.3 on 2025-06-13 18:19

import api.validators
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20250611_0218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('dni_frontal', 'DNI - Frontal'), ('dni_posterior', 'DNI - Posterior'), ('cedula_frontal', 'Cédula - Frontal'), ('cedula_posterior', 'Cédula - Posterior'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro documento')], max_length=20, verbose_name='Tipo de documento')),
                ('archivo_documento', cloudinary.models.CloudinaryField(help_text='Formatos permitidos: JPG, PNG, PDF. Tamaño máximo: 5MB', max_length=255, validators=[api.validators.validate_document_file], verbose_name='Archivo del documento')),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado'), ('resubir', 'Requiere resubir')], default='pendiente', max_length=15, verbose_name='Estado de verificación')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('comentarios_verificacion', models.TextField(blank=True, help_text='Comentarios sobre la verificación o razones de rechazo', verbose_name='Comentarios de verificación')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tamaño_archivo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo (bytes)')),
                ('formato_archivo', models.CharField(blank=True, max_length=10, verbose_name='Formato del archivo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.jugador', verbose_name='Jugador')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Documento de Jugador',
                'verbose_name_plural': 'Documentos de Jugadores',
                'ordering': ['-fecha_subida'],
                'indexes': [models.Index(fields=['jugador', 'estado_verificacion'], name='api_jugador_jugador_6db69a_idx'), models.Index(fields=['fecha_subida'], name='api_jugador_fecha_s_50f000_idx'), models.Index(fields=['tipo_documento'], name='api_jugador_tipo_do_77d60c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado_verificacion__in', ['pendiente', 'verificado'])), fields=('jugador', 'tipo_documento'), name='unique_jugador_tipo_documento')],
            },
        ),
    ]
