# Generated by Django 5.2.3 on 2025-06-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_jugadordocumento'),
    ]

    operations = [
        # Índices para modelo Partido - Filtros más usados en admin
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_partido_completado ON api_partido (completado);",
            reverse_sql="DROP INDEX IF EXISTS idx_partido_completado;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_partido_fecha ON api_partido (fecha);",
            reverse_sql="DROP INDEX IF EXISTS idx_partido_fecha;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_partido_torneo_completado ON api_partido (torneo_id, completado);",
            reverse_sql="DROP INDEX IF EXISTS idx_partido_torneo_completado;"
        ),
        
        # Índices para modelo Equipo - Filtros críticos en admin
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_equipo_activo ON api_equipo (activo);",
            reverse_sql="DROP INDEX IF EXISTS idx_equipo_activo;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_equipo_estado ON api_equipo (estado);",
            reverse_sql="DROP INDEX IF EXISTS idx_equipo_estado;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_equipo_grupo ON api_equipo (grupo);",
            reverse_sql="DROP INDEX IF EXISTS idx_equipo_grupo;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_equipo_categoria_activo ON api_equipo (categoria_id, activo);",
            reverse_sql="DROP INDEX IF EXISTS idx_equipo_categoria_activo;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_equipo_torneo_grupo ON api_equipo (torneo_id, grupo);",
            reverse_sql="DROP INDEX IF EXISTS idx_equipo_torneo_grupo;"
        ),
        
        # Índices para modelo Tarjeta - Filtros frecuentes en admin
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_tarjeta_pagada ON api_tarjeta (pagada);",
            reverse_sql="DROP INDEX IF EXISTS idx_tarjeta_pagada;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_tarjeta_tipo ON api_tarjeta (tipo);",
            reverse_sql="DROP INDEX IF EXISTS idx_tarjeta_tipo;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_tarjeta_tipo_pagada ON api_tarjeta (tipo, pagada);",
            reverse_sql="DROP INDEX IF EXISTS idx_tarjeta_tipo_pagada;"
        ),
        
        # Índices para modelo Jugador - Filtros en admin
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_jugador_suspendido ON api_jugador (suspendido);",
            reverse_sql="DROP INDEX IF EXISTS idx_jugador_suspendido;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_jugador_activo_segunda_fase ON api_jugador (activo_segunda_fase);",
            reverse_sql="DROP INDEX IF EXISTS idx_jugador_activo_segunda_fase;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_jugador_equipo_suspendido ON api_jugador (equipo_id, suspendido);",
            reverse_sql="DROP INDEX IF EXISTS idx_jugador_equipo_suspendido;"
        ),
        
        # Índices para modelo Gol - Optimizar consultas de estadísticas
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_gol_partido ON api_gol (partido_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_gol_partido;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_gol_jugador_partido ON api_gol (jugador_id, partido_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_gol_jugador_partido;"
        ),
        
        # Índices para modelo EstadisticaEquipo - Tabla de posiciones
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_estadistica_torneo_puntos ON api_estadisticaequipo (torneo_id, puntos DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_estadistica_torneo_puntos;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_estadistica_torneo_diferencia ON api_estadisticaequipo (torneo_id, diferencia_goles DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_estadistica_torneo_diferencia;"
        ),
        
        # Índices para TransaccionPago - Filtros financieros
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_transaccion_tipo ON api_transaccionpago (tipo);",
            reverse_sql="DROP INDEX IF EXISTS idx_transaccion_tipo;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_transaccion_es_ingreso ON api_transaccionpago (es_ingreso);",
            reverse_sql="DROP INDEX IF EXISTS idx_transaccion_es_ingreso;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_transaccion_fecha ON api_transaccionpago (fecha);",
            reverse_sql="DROP INDEX IF EXISTS idx_transaccion_fecha;"
        ),
    ]
